freeze('f469-disco/usermods/udisplay_f469/display_unixport')
freeze('f469-disco/libs/common')
freeze('scenarios/MockUI/src')
freeze('src', ('app.py', 'config_default.py', 'errors.py', 'helpers.py',
               'platform.py', 'qrencoder.py', 'rng.py', 'specter.py'))
freeze('src', 'apps')
freeze('src', 'gui')
freeze('src', 'hosts')
freeze('src', 'keystore')
freeze('browser_mockui_entry')
